### ISSUE TITLE
服务端配置修改生效延时怎么控制的啊？

### ISSUE THREAD

**Issue by wingedFish** [apolloconfig/apollo-build-scripts#12]
Hi，我看文章中说 客户端是通过长轮询检测有没有 配置修改，那么就涉及到修改生效延时的问题，请问下这块是如何解决的啊？是通过提高轮询频率吗？还是服务端会在修改后立即通知客户端？

**Comment by nobodyiam** [comment]
服务端在配置修改后会立即通知客户端，具体可以看一下 [NotificationControllerV2.java](https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/controller/NotificationControllerV2.java)
