### ISSUE TITLE
demo.sh有没有windows版本的

### ISSUE THREAD

**Issue by fxltsbl3855** [apolloconfig/apollo-build-scripts#14]
apllo服务端是web应用，理论上在windows下肯定是可以运行的，但是没有对应的win脚本，能否提供一个demo.bat脚本？
非常感谢，我是新手，准备本机装上看看

**Comment by Reason0701** [comment]
在windows上面试了，跑不起来，我jdk明明是1.8，说我jdk小于1.8，报错如下：
,$ ./demo.sh start
Windows new JAVA_HOME is: /c/Program
Files/Java/JDK18~1.0_2
Java version is , please make sure java 1.8+ is in the path

EDZ@ThinkPad-T420 MINGW64 /D/BaiduNetdiskDownload/apollo-build-scripts-master
$ java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

**Comment by nobodyiam** [comment]
git bash的版本是啥？看上去是cygpath这个命令跑出来的java路径不对，带换行了

Windows new JAVA_HOME is: /c/Program
Files/Java/JDK18~1.0_2

**Comment by nobodyiam** [comment]
git bash的版本是啥？看上去是cygpath这个命令跑出来的java路径不对，带换行了

Windows new JAVA_HOME is: /c/Program
Files/Java/JDK18~1.0_2
