### ISSUE TITLE
Quick Start安装包 公网部署问题

### ISSUE THREAD

**Issue by wqwangruiqi** [apolloconfig/apollo-build-scripts#19]
阿里云服务器下载Quick Start安装包 然后部署成功 能够成功登陆后台并操作。
在本地springboot连接阿里云上面apollo出现url连接地址超时 
http://172.17.156.55:8080/notifications/v2?.....
http://172.17.156.55:8080/configs/onechar/default/application?......
我看了地址里面的ip是阿里云局域网ip 不是公网ip 这种情况怎么处理？

**Comment by wulinghui** [comment]
# meta server url 
config_server_url=http://ip:8080
admin_server_url=http://ip:8090
eureka_service_url=$config_server_url/eureka/
portal_url=http://ip:8070

# JAVA OPTS  -Deureka.instance.homePageUrl=http://${指定的IP}:${指定的Port}
BASE_JAVA_OPTS="-Denv=dev"
CLIENT_JAVA_OPTS="$BASE_JAVA_OPTS -Dapollo.meta=$config_server_url"
SERVER_JAVA_OPTS="$BASE_JAVA_OPTS -Dspring.profiles.active=github -Deureka.service.url=$eureka_service_url -Deureka.instance.homePageUrl=$config_server_url"
PORTAL_JAVA_OPTS="$BASE_JAVA_OPTS -Ddev_meta=$config_server_url -Dspring.profiles.active=github,auth -Deureka.client.enabled=false -Dhibernate.query.plan_cache_max_size=192"
