### ISSUE TITLE
deme.sh 启动不了啊

### ISSUE THREAD

**Issue by gaoconggit** [apolloconfig/apollo-build-scripts#25]
错误信息：
 ./service/apollo-service.jar: line 168: /c/Program: No such file or directory

**Comment by gaoconggit** [comment]
win10 下，git bash.

执形的 ./demo.sh start

**Comment by gaoconggit** [comment]
原因是我没配置 JAVA_HOME这个环境变量

**Comment by GirHubCom** [comment]
java_home配置是正确的这个问题也没解决啊，是不是还有其他问题，这个问题早就想过了，脑阔疼，求助

**Comment by nobodyiam** [comment]
@GirHubCom

**Comment by GirHubCom** [comment]
@nobodyiam 感谢回复，这个问题是我纠结了，一直没注意前面作者说的java_home路径不能有空格，win一直默认的就是在C:\Program Files\Java  这个目录，只要换一个目录就好了，./service/apollo-service.jar: line 168: /c/Program: No such file or directory这个问题也不存在了
