### ISSUE TITLE
demo.sh stop时报错 无法关闭8080 8070端口 服务仍正常提供

### ISSUE THREAD

**Issue by ayamzh** [apolloconfig/apollo-build-scripts#28]
on bean with name 'scopedTarget.eurekaClient': org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaInstanceConfigBean': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!

**Comment by nobodyiam** [comment]
看第一条报错信息
