### ISSUE TITLE
demo.sh 在linux下启动连接的数据库是apolloconfigdb.但是demo里面写的数据库连接是ApolloPortalDB

### ISSUE THREAD

**Issue by yeohx** [apolloconfig/apollo-build-scripts#33]
demo.sh 在linux下启动连接的数据库是apolloconfigdb.但是demo里面写的数据库连接是ApolloPortalDB.为什么?是我下载的demo的版本不对么?

**Comment by nobodyiam** [comment]
demo.sh里面有两个数据库连接的配置
