### ISSUE TITLE
怎么修改demo.sh

### ISSUE THREAD

**Issue by Joe798** [apolloconfig/apollo-build-scripts#37]
https://github.com/nobodyiam/apollo-build-scripts#22-配置数据库连接信息
在上面写到：
> 注意：不要修改demo.sh的其它部分

需要修改 demo.sh 情况下如何修改？
例如，https://github.com/ctripcorp/apollo/wiki/分布式部署指南#14网络策略 写到的：
> 另外一种方式是直接指定要注册的IP，可以修改startup.sh，通过JVM System Property在运行时传入，如-Deureka.instance.ip-address=${指定的IP}

**Comment by Joe798** [comment]
@nobodyiam

**Comment by nobodyiam** [comment]
可以修改SERVER_JAVA_OPTS

```bash
SERVER_JAVA_OPTS="$BASE_JAVA_OPTS -Dspring.profiles.active=github -Deureka.service.url=$eureka_service_url"
```
