### ISSUE TITLE
apollo使用的Eureka如何设置注册权限

### ISSUE THREAD

**Issue by yangxueyong** [apolloconfig/apollo-build-scripts#43]
使用apollo/demo.sh start 启动apollo之后，默认使用Eureka作为注册中心，然后我自己创建了一个springboot的工程去，代码里使用apollo.meta=http://ip:8080去链接apollo的注册中心，但是如果我希望在Eureka中设置一个用户名密码使得客户端链接这个Eureka时，必须传入正确的用户名密码才能正常注册，这应该怎样设置？

**Comment by nobodyiam** [comment]
`apollo.meta=http://ip:8080`这个和eureka没关系，客户端不会连eureka，只有config service和admin service才会连eureka
