### ISSUE TITLE
apollo怎么设置adminService和ConfigService的EurekaIP

### ISSUE THREAD

**Issue by NoFindBug** [apolloconfig/apollo-build-scripts#45]
apollo自带的Eureka好像是注册路径是内定的，去那里修改呀，我想把注册Eureka的IP设置成外网IP；我现在的情况是外网可以访问到apollo但是注册中心中的服务路径是内网的IP地址，怎么把内网ip改成外网ip

**Comment by nobodyiam** [comment]
启动参数增加`-Deureka.instance.ip-address=${指定的IP}`即可，也可以通过OS Environment Variable，如`EUREKA_INSTANCE_IP_ADDRESS=${指定的IP}`
