### ISSUE TITLE
Windows demo.sh启动报错

### ISSUE THREAD

**Issue by chenyu9390** [apolloconfig/apollo-build-scripts#47]
java的版本:
![image](https://user-images.githubusercontent.com/8199403/78756592-9edfed80-79ad-11ea-96aa-8b6ea4264983.png)

git for windows的版本：
![image](https://user-images.githubusercontent.com/8199403/78756025-aeab0200-79ac-11ea-927c-24e0e67754c3.png)
启动报错：
![image](https://user-images.githubusercontent.com/8199403/78756187-f762bb00-79ac-11ea-98f7-f2ff6aca7a48.png)

怀疑是不是和java的安装路径中包含空格有关，重新复制了java的安装文件到D:\java文件夹下，在deme.sh中指定路径发现就能正常启动了
![image](https://user-images.githubusercontent.com/8199403/78756626-ab644600-79ad-11ea-9dc3-ad17f7d3d379.png)

**Comment by nobodyiam** [comment]
执行下面的命令看看

```bash
echo "$JAVA_HOME"
tmp_java_home=`cygpath -sw "$JAVA_HOME"`
echo "$tmp_java_home"
JAVA_HOME=`cygpath -u $tmp_java_home`
echo "$JAVA_HOME"
```
