### ISSUE TITLE
配置多环境文件

### ISSUE THREAD

**Issue by hnliuli** [apolloconfig/apollo-build-scripts#51]
当我在portal数据的serverconfig表里面增加apollo.portal.meta.servers值来配置多个环境的时候，单选择除dev以外的环境都报错，是不支持还是demo.sh里面少配置了什么东西
![图片](https://user-images.githubusercontent.com/65536510/82195446-e487c280-992a-11ea-9952-4bb895175690.png)
![图片](https://user-images.githubusercontent.com/65536510/82195872-80b1c980-992b-11ea-9590-766a4c78448f.png)

**Comment by nobodyiam** [comment]
多环境的数据库元数据是否都初始化好了？参考下[从别的环境导入ApolloConfigDB的项目数据](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#2121-%E4%BB%8E%E5%88%AB%E7%9A%84%E7%8E%AF%E5%A2%83%E5%AF%BC%E5%85%A5apolloconfigdb%E7%9A%84%E9%A1%B9%E7%9B%AE%E6%95%B0%E6%8D%AE)
