### ISSUE TITLE
系统出错，请重试或者联系负责人

### ISSUE THREAD

**Issue by nathenaochen** [apolloconfig/apollo-build-scripts#52]
启动8070portal端口后，创建项目或者点击SampleApp进入配置界面报错，系统出错，请重试或者联系负责人，访问http://ip:8070端口进行检查时，报错{"exception":"org.springframework.transaction.CannotCreateTransactionException","message":"Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection","status":500,"timestamp":"2020-05-28T18:04:49.782"}

**Comment by nobodyiam** [comment]
看下 portal 和 adminservice 的日志
