### ISSUE TITLE
Fail to start

### ISSUE THREAD

**Issue by hundanLi** [apolloconfig/apollo-build-scripts#54]
Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could
be configured.

**Comment by sparic** [comment]
+1

**Comment by wanghuashun** [comment]
你们是不是用的外部的mysql

**Comment by hundanLi** [comment]
> 你们是不是用的外部的mysql

localhost

**Comment by wanghuashun** [comment]
我的也是localhost  导入的文档中的表结构  就是链接不上  感觉表结构有问题

**Comment by nobodyiam** [comment]
看描述是数据库url没有配置，你确定是用demo.sh启动的？

**Comment by hexiaoming123** [comment]
我也遇到同样问题

**Comment by hexiaoming123** [comment]
我使用百度网盘1.5.1.zip的快速启动项目更改了为300s启动起来了，使用1.7.0的无法启动

**Comment by hundanLi** [comment]
> 看描述是数据库url没有配置，你确定是用demo.sh启动的？

确定
