### ISSUE TITLE
8070端口启动不起来，./apollo-protal.jar没有创建

### ISSUE THREAD

**Issue by MarlboroLeo** [apolloconfig/apollo-build-scripts#55]
redhat系统
错误日志：
ERROR 24282 -- [TaskBatchingworker-target_128.192.199.199-3] c.n.e.cluster.ReplicationTaskprocessor   :  Network level connection to peer 128.192.199.199; retrying after delay

求助 谢谢

**Comment by MarlboroLeo** [comment]
@nobodyiam

**Comment by nobodyiam** [comment]
看下完整的日志吧

**Comment by yang-jbc** [comment]
demo.sh里
PORTAL_DIR=./portal
PORTAL_JAR_NAME=apollo-portal.jar
PORTAL_JAR=$PORTAL_DIR/$PORTAL_JAR_NAME

该文件不存在！

**Comment by nobodyiam** [comment]
@yang-jbc 脚本会自动拷贝一份出来的
