### ISSUE TITLE
docker快速部署想使用自己的mysql

### ISSUE THREAD

**Issue by wanghuashun** [apolloconfig/apollo-build-scripts#56]
我如何是使用后外部的数据库 不启动mysql容器 使用外部的mysql导入里面的sql语句 我改了改把mysql链接替换到demo.sh脚本，项目就启动不了

**Comment by nobodyiam** [comment]
看下具体的错误信息吧

**Comment by wanghuashun** [comment]
Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could
be configured.

**Comment by nobodyiam** [comment]
@wanghuashun 需要配置下数据库的访问信息，可以参考下面的脚本

https://github.com/nobodyiam/apollo-build-scripts/blob/99667c59ff845a0defe1d3a5421c6789ed3f423b/Dockerfile#L24
