### ISSUE TITLE
按官方quick start启动报数据相关错误

### ISSUE THREAD

**Issue by banzhiguo** [apolloconfig/apollo-build-scripts#58]
注：
1、我在win10上启动，在git bash下 ./demo.sh start
2、demo.sh配置修改如下：
apollo_config_db_url=jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8
apollo_config_db_username=root
apollo_config_db_password=123456

# apollo portal db info
apollo_portal_db_url=jdbc:mysql://localhost:3306/ApolloPortalDB?characterEncoding=utf8
apollo_portal_db_username=root
apollo_portal_db_password=123456

错误1：Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
错误2：Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
错误3：Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#73f6c731': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]

**Comment by nobodyiam** [comment]
有更多的 Caused by 信息吗？

**Comment by banzhiguo** [comment]
把demo.sh中的characterEncoding=utf8去掉并且加上serverTimezone=UTC就好了



---原始邮件---
发件人: "Jason Song"<notifications@github.com&gt;
发送时间: 2020年12月10日(周四) 上午9:15
收件人: "nobodyiam/apollo-build-scripts"<apollo-build-scripts@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"banzhiguo"<516544181@qq.com&gt;;
主题: Re: [nobodyiam/apollo-build-scripts] 按官方quick start启动报数据相关错误 (#58)




 
有更多的 Caused by 信息吗？

**Comment by banzhiguo** [comment]
搜索工具
百度为您找到

demo.sh的mysql链接去掉characterEncoding=utf8，加上servertimezone=utc就好了
相关结果约21,000,000个



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nobodyiam/apollo-build-scripts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月10日(星期四) 上午9:14
收件人:&nbsp;"nobodyiam/apollo-build-scripts"<apollo-build-scripts@noreply.github.com&gt;;
抄送:&nbsp;"峩主载... o"<516544181@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nobodyiam/apollo-build-scripts] 按官方quick start启动报数据相关错误 (#58)





 
有更多的 Caused by 信息吗？
