### ISSUE TITLE
参考无法启动

### ISSUE THREAD

**Issue by mailxlah** [apolloconfig/apollo-build-scripts#59]
Error creating bean with name 'eurekaInstanceConfigBean': Singleton bean creation not allowed while singletons of this factory are in destruction

**Comment by mailxlah** [comment]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-12-09 19:52:30.118 ERROR 2800 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine suitable jdbc url

**Comment by nobodyiam** [comment]
看上去是数据库地址没有指定
