### ISSUE TITLE
demo.sh启动报错

### ISSUE THREAD

**Issue by X-Zackt** [apolloconfig/apollo-build-scripts#66]
root@localhost apollo-build-scripts]# ./demo.sh start
==== starting service ====
Service logging file is ./service/apollo-service.log
Application is running as root (UID 0). This is considered insecure.
Failed to start
Failed to start service, return code: 1. Please check ./service/apollo-service.log for more information.

我查看并没有apollo-service.log

demo.sh我只改了数据库的配置

**Comment by nobodyiam** [comment]
./service 目录下应该有日志的，或者看下是否有写权限

**Comment by X-Zackt** [comment]
> ./service 目录下应该有日志的，或者看下是否有写权限

[root@localhost service]# ll
总用量 75228
drwxr-xr-x. 2 root root       32 4月  21 16:14 apollo-service
-rw-r--r--. 1 root root      205 4月  21 14:00 apollo-service.conf
-rwxr-xr-x. 2 root root 77019480 4月  21 14:00 apollo-service.jar
-rw-r--r--. 1 root root     6564 4月  21 19:01 console.log
[root@localhost service]# id
uid=0(root) gid=0(root) 组=0(root) 环境=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
[root@localhost service]# 

root用户登录 写权限肯定是有的。

**Comment by nobodyiam** [comment]
看下 console.log

**Comment by X-Zackt** [comment]
[root@localhost service]# vim console.log 

start-stop-daemon: unrecognized option '--no-close'
BusyBox v1.27.0 (2017-07-11 11:17:13 CST) multi-call binary.

Usage: start-stop-daemon [OPTIONS] [-S|-K] ... [-- ARGS...]

Search for matching processes, and then
-K: stop all matching processes.
-S: start a process unless a matching process is found.

Process matching:
        -u,--user USERNAME|UID  Match only this user's processes
        -n,--name NAME          Match processes with NAME
                                in comm field in /proc/PID/stat
        -x,--exec EXECUTABLE    Match processes with this command
                                in /proc/PID/{exe,cmdline}
        -p,--pidfile FILE       Match a process with PID from the file
        All specified conditions must match
-S only:
        -x,--exec EXECUTABLE    Program to run
        -a,--startas NAME       Zeroth argument
        -b,--background         Background
        -N,--nicelevel N        Change nice level
        -c,--chuid USER[:[GRP]] Change to user/group
        -m,--make-pidfile       Write PID to the pidfile specified by -p
-K only:
        -s,--signal SIG         Signal to send
        -t,--test               Match only, exit with 0 if a process is found
Other:
        -o,--oknodo             Exit with status 0 if nothing is done
        -v,--verbose            Verbose
        -q,--quiet              Quiet
start-stop-daemon: unrecognized option '--no-close'
BusyBox v1.27.0 (2017-07-11 11:17:13 CST) multi-call binary.

Usage: start-stop-daemon [OPTIONS] [-S|-K] ... [-- ARGS...]

Search for matching processes, and then
-K: stop all matching processes.
-S: start a process unless a matching process is found.

Process matching:
        -u,--user USERNAME|UID  Match only this user's processes
        -n,--name NAME          Match processes with NAME
                                in comm field in /proc/PID/stat
        -x,--exec EXECUTABLE    Match processes with this command
                                in /proc/PID/{exe,cmdline}

**Comment by nobodyiam** [comment]
参考下 #5，https://github.com/ctripcorp/apollo/issues/2147
