### ISSUE TITLE
portal.jar return 126

### ISSUE THREAD

**Issue by zhanghaofei** [apolloconfig/apollo-build-scripts#7]
```
Portal logging file is ./portal/apollo-portal.log
./demo.sh: line 155: ./portal/apollo-portal.jar: Invalid argument
Failed to start portal, return code: 126. Please check ./portal/apollo-portal.log for more `information.`
```
但是并没有 ./portal/apollo-portal.log这个日志文件

**Comment by nobodyiam** [comment]
你是在什么OS环境运行的？

**Comment by zhanghaofei** [comment]
ubuntu 16:04

**Comment by zhanghaofei** [comment]
是jdk问题吗？我安装的openjdk-8-jdk

**Comment by zhanghaofei** [comment]
不行，换了oracle的一样

**Comment by nobodyiam** [comment]
是不是改的demo.sh有点问题？我看github上的155行是空行。。。

https://github.com/nobodyiam/apollo-build-scripts/blob/master/demo.sh#L155

**Comment by zhanghaofei** [comment]
忘记跟你说了，是154行报这个错，然后我注释了后面复制一行把后面--的参数去掉了，也一样，，其实就是154行。之后我直接手动执行那个./portal/apollo-portal.jar 加和不加参数都报这个错

**Comment by nobodyiam** [comment]
其实[110行](https://github.com/nobodyiam/apollo-build-scripts/blob/master/demo.sh#L110)和[154](https://github.com/nobodyiam/apollo-build-scripts/blob/master/demo.sh#L154)行是一样的，不应该110行执行成功，154行执行失败的。

要不你试试从百度网盘下载吧，https://pan.baidu.com/s/1skRAQfV

**Comment by zhanghaofei** [comment]
又试了一样的报错

**Comment by nobodyiam** [comment]
这两行的jar其实是同一个，你算一下sha1sum就知道了。
