### ISSUE TITLE
ConfigUtil跟ApolloApplicationContextInitializer的加载顺序

### ISSUE THREAD

**Issue by XiongHui-2016** [apolloconfig/apollo-build-scripts#70]
项目中遇到一个问题，
问题描述：
1. 在application.properties中配置了
`apollo.bootstrap.enabled=true
apollo.bootstrap.eagerLoad.enabled=true
apollo.bootstrap.namespaces=application
app.id=
apollo.cluster=gray`
但是项目启动时并获取不到apollo.cluster的值，经过debug发现，apollo.cluster值是在ConfigUtil初始化的时候从System.getProperty中取值的，而application.properties配置的参数是在ApolloApplicationContextInitializer中initializeSystemProperty到环境变量中去的。
2. 现在dubug的顺序是ConfigUtil先于ApolloApplicationContextInitializer加载
问题：怎么调整他们两的加载顺序

**Comment by nobodyiam** [comment]
这个我测试下来是没问题的，建议再排查下，或者可以上传个最简 demo

**Comment by XiongHui-2016** [comment]
好的，目前已经改成-D的方式处理了，后续我再排查下原因。
