### ISSUE TITLE
修改apollo-all-in-one.jar

### ISSUE THREAD

**Issue by xuyeba** [apolloconfig/apollo-build-scripts#8]
想修改一下页面的样式，于是修改了apollo-all-in-one.jar里面的某个jar包的静态文件，改完后发现保存不了，apollo-all-in-one.jar这个jar包是做了什么限制了吗，是不是不运行修改的？

**Comment by nobodyiam** [comment]
是的，这个是spring boot打包的，在jar包头上有脚本信息的，apollo-all-in-one只是用来demo的，如果要修改的话，建议在原始的[Apollo项目](https://github.com/ctripcorp/apollo)上进行，可以通过IDE在本机开发，具体可以参考Apollo项目的wiki页面。
