### ISSUE TITLE
docker-compose lose some docker image 

### ISSUE THREAD

**Issue by wenchaomartin** [apolloconfig/apollo-build-scripts#82]
` i install dokcer  desktop docker in win10 ver19043 `

`git clone the apollo-build-scripts` 

cd ` apollo-build-scripts` in local  git directory 

type the cmd of  `docker-compose up`

the   occure the  error in the screen 

`ERROR: pull access denied for apollo-quick-start, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

then i login in the  cmd    but not work 

occure the error agin 

`ERROR: pull access denied for apollo-quick-start, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

**Comment by nobodyiam** [comment]
This repository is for the purpose to build docker image locally. If you want to use an existing image, you could use the docker-compose.yml from the [docker-quick-start](https://github.com/apolloconfig/apollo/tree/master/scripts/docker-quick-start) in apollo main repository instead.

**Comment by wenchaomartin** [comment]
i understand u you said, if i use the docker-comopose file in this project ,
 
 i must build the docker-file to image. 
 
 and then run the cmd of docker-compose up .

**Comment by nobodyiam** [comment]
That's correct.
