### ISSUE TITLE
启动demo.sh的时候报jdk版本问题

### ISSUE THREAD

**Issue by ForeverKang** [apolloconfig/apollo-build-scripts#83]
我是jdk11版本，但是启动demo.sh的时候报版本不能低于1.8
**Java version is 11.0.13, please make sure java 1.8+ is in the path**
这个问题如何解决

**Comment by nobodyiam** [comment]
The java version check logic is as follows, but it's strange that it works in my environment (mac os).
You may first comment the version check logic. BTW, what's your operating environment?

https://github.com/apolloconfig/apollo-build-scripts/blob/fa578778c9f0b707b26661c4104236b720eedb71/demo.sh#L89-L96

**Comment by nobodyiam** [comment]
Another solution is to transform the version string to digits

```bash
      version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
      version_in_digit=$(echo "$version" | awk -F. '{printf("%03d%03d",$1,$2);}')
      if [[ $version_in_digit < 001008 ]]; then
          echo "Java version is $version, please make sure java 1.8+ is in the path"
          exit 1
      fi
```
