### ISSUE TITLE
小小建议：apollo_config_db_url也支持变量输入

### ISSUE THREAD

**Issue by huadahuang1983** [apolloconfig/apollo-build-scripts#86]
提个小小建议，在demo.sh中，增加apollo_config_db_url，apollo_portal_db_url支持变量输入，和帐户密码一样。
在实际工作中，我们还是有可能使用旧的或其它方式安装的数据库的。虽然我们研发人员可以改，但是做成标准的，更稳定通用，更方便大家。

**Comment by nobodyiam** [comment]
That sounds like a good idea! Are you interested in submitting a pull request for this feature?
