### ISSUE TITLE
如何设置adminservice也就是 eurika的端口

### ISSUE THREAD

**Issue by R1310328554** [apolloconfig/apollo-build-scripts#9]
portal 的端口我知道设置， 但是 eurika的端口呢？

**Comment by nobodyiam** [comment]
quick start的代码比较特殊，所以不能单独设置admin service的端口。

正常部署可以参考[分布式部署指南](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97)，通过这个方式可以很方便的设置config service, admin service和portal的端口。
